import type { LucideIcon } from "lucide-react"
import {
  Home,
  KeyRound,
  TrendingUp,
  ShoppingBag,
  ShoppingCart,
  Shield,
  Utensils,
  Car,
  Repeat,
  Baby,
  Palmtree,
  Plane,
  Clapperboard,
  GraduationCap,
  Cloud,
  Landmark,
  HeartPulse,
  Sparkles,
  Gift,
  Briefcase,
  Receipt,
  CreditCard,
  Cat,
  Sprout,
  Smartphone,
  Zap,
  Users,
  Wallet,
  RotateCcw,
  ArrowLeftRight,
  Tag,
} from "lucide-react"

// Category -> real SVG icon (no emoji). Falls back to a generic tag.
const CATEGORY_LUCIDE: Record<string, LucideIcon> = {
  household: Home,
  rent: KeyRound,
  housing: Home,
  "savings & investments": TrendingUp,
  savings: TrendingUp,
  shopping: ShoppingBag,
  groceries: ShoppingCart,
  insurance: Shield,
  dining: Utensils,
  transportation: Car,
  subscriptions: Repeat,
  "kids fund": Baby,
  family: Users,
  "vacation fund": Palmtree,
  vacation: Palmtree,
  travel: Plane,
  entertainment: Clapperboard,
  education: GraduationCap,
  cloud: Cloud,
  banking: Landmark,
  healthcare: HeartPulse,
  "personal care": Sparkles,
  "gifts & donations": Gift,
  "professional services": Briefcase,
  taxes: Receipt,
  "debt payments": CreditCard,
  pets: Cat,
  "home & garden": Sprout,
  telecom: Smartphone,
  utilities: Zap,
  income: Wallet,
  refund: RotateCcw,
  transfer: ArrowLeftRight,
}

export function getCategoryLucideIcon(category: string): LucideIcon {
  return CATEGORY_LUCIDE[category.toLowerCase()] ?? Tag
}
